// Generated by CoffeeScript 1.10.0
(function() {
  var _, ast, parse, parser;

  ast = require("./ast.js");

  parser = require("./sqlfull.js");

  _ = require("underscore");

  _.extend(this, ast);

  parse = function(str, DEBUG) {
    var prepareString;
    if (DEBUG == null) {
      DEBUG = true;
    }
    prepareString = function(str) {
      var q;
      q = str;
      q = q.trim();
      q = q.replace(/[\t\n\r]/g, " ");
      q = q.replace(/(\s)+/g, " ");
      q = q.replace(/\(\s+/g, "(");
      q = q.replace(/\s+\)/g, ")");
      return q;
    };
    if (DEBUG) {
      console.log(str);
    }
    return parser.parse(prepareString(str));
  };

  _.extend(parse, ast);

  module.exports = parse;

}).call(this);
