// Generated by CoffeeScript 1.12.2
(function() {
  var _, ast, parse, parser,
    slice = [].slice;

  ast = require("./ast.js");

  parser = require("./sqlfull.js");

  _ = require("underscore");

  _.extend(this, ast);

  parse = function(str, DEBUG) {
    var prepareString;
    if (DEBUG == null) {
      DEBUG = false;
    }
    prepareString = function(str) {
      var q;
      q = str;
      q = q.trim();
      q = q.replace(/[\t\n\r]/g, " ");
      q = q.replace(/(\s)+/g, " ");
      q = q.replace(/\(\s+/g, "(");
      q = q.replace(/\s+\)/g, ")");
      return q;
    };
    if (DEBUG) {
      console.log(str);
    }
    return parser.parse(prepareString(str));
  };

  _.extend(parse, ast);

  parse.one = function() {
    var args, res;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    res = parse.apply(null, args);
    return res.queries[0];
  };

  module.exports = parse;

}).call(this);
